### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by cormullion** [cormullion/graphics#1]
@xgandibleux 

Feeling like simple is best today.

<img width="824" alt="Screenshot 2019-05-29 at 17 18 08" src="https://user-images.githubusercontent.com/52289/58573621-0c6fa900-8236-11e9-89c1-62d1fea77819.png">

**Comment by cormullion** [comment]
A simple single color version... 

![lux-256](https://user-images.githubusercontent.com/52289/58583195-6464da80-824b-11e9-8dba-5b3d06c8a120.png)

**Comment by xgandibleux** [comment]
I like the grey version and the summer version

**Comment by cormullion** [comment]
I'm thinking there are four versions of a design:

- colored to print onto a dark/black background
- colored to print onto a light/white/grey background
- single color (eg black, red, etc) to print onto a dark/black background
- single color (eg black, red, etc) to print onto a light/white/grey background

(eg see `images/` here.)

Let me know the design you want and I can generate the four images (in PNG and SVG).
