### ISSUE TITLE
Updated version of the 2022 REPL T-shirt

### ISSUE THREAD

**Issue by logankilpatrick** [cormullion/graphics#10]
Hey @cormullion! Can we get an updated version of the 2022 REPL T-shirt: https://github.com/cormullion/graphics/blob/master/juliacon2022/tshirts/julia-tshirt-5.svg

We should probably make it say 1.8 since that version will likely be out soon. It might make sense to wait a little and see, no rush on this.

**Comment by cormullion** [comment]
Yes, my mouse pointer is already hovering over the Download button in anticipation. 😂

**Comment by logankilpatrick** [comment]
This is done! Thank you!
