### ISSUE TITLE
Julia themed license plate frame

### ISSUE THREAD

**Issue by logankilpatrick** [cormullion/graphics#11]
Hey! I have had a few people ask for this, here is the design template if you have any ideas for what we can do:
[622219069013d6003d398f69.zip](https://github.com/cormullion/graphics/files/8934471/622219069013d6003d398f69.zip)

All my ideas have to do with speed puns that probably aren't the best fit for a license plate 😄

**Comment by cormullion** [comment]
Hmm, I have no idea! I've never designed one before - I would imagine they're very illegal over here... 

Just because Jurassic World has been released:

<img width="1176" alt="Screenshot 2022-06-19 at 16 50 31" src="https://user-images.githubusercontent.com/52289/174489529-e885d742-9a8b-4b7d-b3a5-fff95b348307.png">

But I'm clueless really... :)

**Comment by logankilpatrick** [comment]
I actually kinda like this (though the new Jurassic World was a solid 4/10). Maybe instead of dinos it could be various Julia package icons? Or just science symbols in general? Or some Julia code?

**Comment by logankilpatrick** [comment]
Yes this looks awesome, for the colors, can we just alternate red, green, and blue for the non screw holes?

**Comment by cormullion** [comment]
If you could sell purple screw covers, it might look quite decent! 

![license-plate](https://user-images.githubusercontent.com/52289/175556740-2d71ee35-9904-4f82-b0b3-9d99865c5354.png)

**Comment by logankilpatrick** [comment]
I am ordering myself one of these right now! Do you want me to send you one as well?

**Comment by cormullion** [comment]
Nice thought - but almost certainly illegal over here!  I’d love to see it affixed to your flashy car though!

**Comment by logankilpatrick** [comment]
Okay I will affix to my not so flashy car and send you a picture

**Comment by cormullion** [comment]
Oh, I had you down as owning one of these: https://media.daimler.com/marsMediaSite/de/instance/ko.xhtml?rs=0&ls=L2VuL2luc3RhbmNlL2tvLnhodG1sP29pZD00ODM2MjU4JnJlbElkPTYwODI5JmZyb21PaWQ9NDgzNjI1OCZib3JkZXJzPXRydWUmcmVzdWx0SW5mb1R5cGVJZD00MDYyNiZ2aWV3VHlwZT10aHVtYnM!&oid=44950205

**Comment by logankilpatrick** [comment]
hahaha I have a model 3 but it's not nearly as fancy as the EQS

**Comment by logankilpatrick** [comment]
It should still make for some good pictures once it comes in!
