### ISSUE TITLE
Update text in JuliaCon 2023 CFP image

### ISSUE THREAD

**Issue by logankilpatrick** [cormullion/graphics#12]
This image: https://github.com/cormullion/graphics/blob/master/juliacon2023/call-for-submissions.svg says 2022 instead of 2023 in the text. Can you update this so I can share it out?

**Comment by cormullion** [comment]
(You can also message me at `@cormullion@julialang.social`... :))

**Comment by logankilpatrick** [comment]
Thank you : )
