### ISSUE TITLE
JuliaCon 2023 T-shirt designs

### ISSUE THREAD

**Issue by logankilpatrick** [cormullion/graphics#14]
Hey @cormullio ! I hope all is well, would you be willing to help put together some MIT CSAIL themed t-shirt designs? As always, the offer stands to pay you for this work : )

**Comment by cormullion** [comment]
Hi, Logan - long time no see! Always happy to help - and of course, it's my contribution to open-source... 😇

There are quite a few t-shirt designs here already, so I gather you're looking for something MIT-specific?

**Comment by cormullion** [comment]
By CSAIL you mean that weird building outline? It might work, on dark background:

<img width="406" alt="Screenshot 2023-06-29 at 09 46 35" src="https://github.com/cormullion/graphics/assets/52289/52a4fb23-dece-4768-8b3d-0b7f9330b5e7">
<img width="356" alt="Screenshot 2023-06-29 at 09 46 28" src="https://github.com/cormullion/graphics/assets/52289/4878e6b6-e7e8-4779-93cc-da469bca39de">
<img width="312" alt="Screenshot 2023-06-29 at 09 46 22" src="https://github.com/cormullion/graphics/assets/52289/777c70c7-4817-451f-9e5c-07d51056074b">
<img width="302" alt="Screenshot 2023-06-29 at 09 46 14" src="https://github.com/cormullion/graphics/assets/52289/a0eba7ee-c0e2-4197-9a85-183bf232bf6a">
<img width="290" alt="Screenshot 2023-06-29 at 09 54 59" src="https://github.com/cormullion/graphics/assets/52289/ce6c01ca-4abc-48ac-bb14-5d07a9798feb">

If you didn't have the text, it would be a bit subtle...

**Comment by cormullion** [comment]
Is there a vector (SVG) version of the Boston graphic used on the juliacon.org page? That could be useful too...

**Comment by cormullion** [comment]
By the way, I saw this the other day - might be useful reading for inclusive t-shirt designs:

https://geekfeminism.fandom.com/wiki/T-shirts

**Comment by aviks** [comment]
I don't think we have a license for putting the Boston graphics in a t-shirt. It's a web only license as far as I remember

**Comment by aviks** [comment]
I really like number 5 above.

**Comment by IanButterworth** [comment]
@cormullion it strikes me that the csail logo looks a little like "julia". 

What about something like

<img width="243" alt="Screenshot 2023-06-29 at 12 19 39 PM" src="https://github.com/cormullion/graphics/assets/1694067/f28b2f7b-555b-4b43-b688-ca9c4c638b28">

**Comment by cormullion** [comment]
@IanButterworth There's definitely something there...! It's all starting to make sense now... :) 

It's sometimes the case that organizations don't like people messing around with their logos too much. I suppose it might be possible to conjure up this building in other non-copyrightable ways:

<img width="205" alt="Screenshot 2023-06-29 at 17 40 33" src="https://github.com/cormullion/graphics/assets/52289/255dc874-78d5-4fe1-b195-2f3d9c9c3e7e">

<img width="332" alt="Screenshot 2023-06-29 at 17 40 57" src="https://github.com/cormullion/graphics/assets/52289/38fb91e4-29bb-46d9-b4a2-f1d05056d7a2">

<img width="368" alt="Screenshot 2023-06-29 at 17 43 10" src="https://github.com/cormullion/graphics/assets/52289/599685f8-3097-4db0-ad54-c720615bbfb6">

**Comment by ranjanan** [comment]
I really like the first image here.

**Comment by Wimmerer** [comment]
@cormullion would it be possible to give the silhouette here a try? https://www.csail.mit.edu/sites/default/files/styles/primary_image/public/2018-03/8IJ6bTBzzeY9tTRAlCWkX_kQnn_bObdSidVptT1DAo8%2Ce55rYzWwNNl0zT4Yl2KvNczCALF8vnVAnT_tiMcok-M_1.jpg?h=ac9c78f9&itok=cQe5KIG4

Imho it's a more recognizable silhouette.

If it's a lot of work no worries!

**Comment by ranjanan** [comment]
Could you also attach high res PNGs of 
![](https://user-images.githubusercontent.com/52289/249843550-255dc874-78d5-4fe1-b195-2f3d9c9c3e7e.png) and 
![](https://user-images.githubusercontent.com/52289/249723620-ce6c01ca-4abc-48ac-bb14-5d07a9798feb.png)
 please? Thank you so much as always for producing these brilliant graphics!

**Comment by cormullion** [comment]
@ranjanan Sure - [here](https://github.com/cormullion/graphics/tree/master/juliacon2023/t-shirts)
@Wimmerer I'll have a look!

**Comment by cormullion** [comment]
@Wimmerer perhaps a bit too crazy...

<img width="469" alt="Screenshot 2023-07-04 at 12 13 04" src="https://github.com/cormullion/graphics/assets/52289/082d6ca7-81e4-4604-b825-0ed10d0887b1">

**Comment by ranjanan** [comment]
We spoke to our MIT contact and they rejected both of these designs. They require multiple levels of permission. 

@cormullion I am very sorry to waste your time, but we have been brainstorming backup options. Are any of these low hanging fruit for you for a T shirt design: 
1. The JuliaLab logo here: https://avatars.githubusercontent.com/u/20145488?s=200&v=4, or  
![julia-lab-logo](https://github.com/cormullion/graphics/assets/9101377/c5f8e1ac-0e2f-4b66-be5c-fdc4f031289e)
This is nice and appropriate but very barebones. The second logo also already has Julia on it. 
2. A minuteman: 
![image](https://github.com/cormullion/graphics/assets/9101377/46392e35-e8f6-4558-b759-a8a588db8561)
3. A lighthouse: 
![image](https://github.com/cormullion/graphics/assets/9101377/dc661fcf-86f6-4182-aaed-ad0858f87a31)

**Comment by cormullion** [comment]
haha - some very, er, USA, ideas, and why not... 🇺🇸🇺🇸🇺🇸

I'll try to come up with some. 

I added a REPL shirt, of course. [here](https://github.com/cormullion/graphics/tree/master/juliacon2023/t-shirts)

And I made a Lorenz attractor one, too, after I discovered that he was at MIT for most of his career.

**Comment by ranjanan** [comment]
Haha, yes they're actually Massachusetts specific more than USA specific. There isn't an obvious answer here because I expected them to be okay with one of the designs.

**Comment by IanButterworth** [comment]
Maybe the repl shirt needs updating because it's both local and remote now... 
Also, it also should've `@everywhere`'d `using JuliaCon` really :)
```
julia> using MIT, Distributed

julia> @everywhere import JuliaCon 

julia> @everywhere JuliaCon.juliacon2023()
```

**Comment by Wimmerer** [comment]
@IanButterworth they don't want us to put MIT on the shirt... 😢

**Comment by Wimmerer** [comment]
@cormullion for cost reasons the shirt will probably be smushed down to 5 or so colors. Is there a gradient on the Lorenz dots? Can they be flat?

**Comment by cormullion** [comment]
@Wimmerer sure, I'll do something first thing tomorrow morning 🥱

**Comment by ranjanan** [comment]
Thanks so much as always @cormullion!

**Comment by cormullion** [comment]
It's a pity that the buildings are copyrighted... Otherwise you could have 

<img width="238" alt="Screenshot 2023-07-06 at 11 40 09" src="https://github.com/cormullion/graphics/assets/52289/e35ef63e-41ff-465d-987e-952422985ce9">

I added a few more.

**Comment by Wimmerer** [comment]
@cormullion The last one is clever :P!!! We're probably going to get stickers of it (less "what does this mean?" questions than on the main t-shirt)!
