### ISSUE TITLE
JuliaCon Miscellaneous

### ISSUE THREAD

**Issue by Wimmerer** [cormullion/graphics#15]
Hey Cormullion,

We have a few more designs needed for JuliaCon:

- [ ] A waiting screen for when tracks are not running. This can be static or potentially a video. We'll probably want a video for the YouTube uploads regardless so both would be nice.
- [ ] A Picture-in-Picture screen. This should have a large blank space for the actual presentation and a blank space for the speaker in a bar on the side. Beneath the speaker picture we should have our biggest sponsors. Probably the silver and above sponsors from here: https://juliacon.org/2023/. I'm not sure what format this would be required in, but if you can give me something that can easily be converted to whatever MIT AV will need that would be fantastic.
- [ ] A large format poster. I will update on the exact contents for this. I think there's a good design for a small format background, but let Ranjan and I figure out what elements we need for large ones!

**Comment by cormullion** [comment]
Sure, I'd love to make some things...!

usually 1920x1080 (1080p) works ok...

for 1: I could do something like this sample - although it's better when it's about 1 minute duration, where the fades can be slower (about 5 seconds)...

https://github.com/cormullion/graphics/assets/52289/54a3e9bf-9555-44c2-aa8f-ae4d2665253f

for 2: Have you got a template for the dimensions?  Might be easier to make it to some standard...

Also - somewhere I can upload stuff for you would be great, in case github complains.

Hope to see you on Monday anyway!

**Comment by Wimmerer** [comment]
1920x1080 will be perfect. If we could get the short version, a long version like you mentioned, and then maybe also a static image that would be great. 

We'll probably do a few posters that are just normal printer paper, and then we'll do a few big posters. Perhaps a few that are 36" x 48" (portrait orientations), and then a few smaller ones with the same aspect ratio.

A template for the posters would be great, since we'll need to add things to them like wayfinding and such. I'll send you somewhere to upload them in a bit once Ranjan gets here!

Looking forward to seeing you!

**Comment by Wimmerer** [comment]
Oh also do you have the logos for JuMP, SciML and ASE60 available as individual images?

**Comment by Wimmerer** [comment]
@cormullion oh also real quick are you able to make me a template of the blanktemplate files in portrait for 11 x 8.5 aspect ratio?

**Comment by cormullion** [comment]
there wasn’t really a logo for ASE60, just a big photo of Alan  😂 but I made something simple for a template for Steve - that what you mean?

**Comment by Wimmerer** [comment]
The one that you have on the blanktemplates files works great!

The thing I need most immediately though is higher def versions of those blanktemplate files in juliacon2023 folders. Something that will print well at 8.5"x11".

**Comment by Wimmerer** [comment]
@cormullion do you have an email or are you on Slack?

**Comment by cormullion** [comment]
cormullion@mac.com - also Discourse, Zulip, Github, and Mastodon. And I’m 5 hours ahead of you 😂

**Comment by Wimmerer** [comment]
Oof it's already late there isn't it. Let me send you an email on what we're ordering and get your thoughts there.

**Comment by Wimmerer** [comment]
@cormullion could we get the Picture-in-Picture screen today?

**Comment by cormullion** [comment]
Yes , sure - is there any guide to dimensions or areas at all?

**Comment by Wimmerer** [comment]
1920x1080. Maximizing display size of course, but still with a good size view of the presenter.

**Comment by cormullion** [comment]
@Wimmerer I'm not sure what the Picture-in-Picture should look like - can you sketch the basics out for me?

The 24"x36" are quite big PNG files now. (the fractal isn't SVG unfortunately).

**Comment by Wimmerer** [comment]
It's like this video: https://www.youtube.com/watch?v=ubURNGq6lsI, where there's a video feed of the speaker and a video feed of the presentation. If you could make one with no sponsors and with JuliaHub / ASML and the three silver sponsors also (pumas, quera, relational) below the speaker on the sidebar that would be perfect.

It's essentially just the layout of the streams. Picture-in-Picture might be the wrong word :/ :)

**Comment by Wimmerer** [comment]
That should be perfect! I suppose it doesn't need cut outs they'll just plop the streams on top! 

Thanks!

**Comment by cormullion** [comment]
OK, I uploaded those....
