### ISSUE TITLE
YouTube banners

### ISSUE THREAD

**Issue by cormullion** [cormullion/graphics#16]
@ViralBShah Hi Viral! 

I added a few new YouTube banners (2560x1440) to this repo, now that the JuliaCon2023 banner is starting to become out-of-date:

https://github.com/cormullion/graphics/tree/master/youtube-banners-aug-2023

<img width="1396" alt="Screenshot 2023-08-19 at 18 01 20" src="https://github.com/cormullion/graphics/assets/52289/d865b302-8781-429c-9aea-094fd6d5264c">

(graphics made with Julia at least)

I might still have admin access to the YouTube channel myself (from a few years ago) so in theory I could change the banners now, but I prefer asking/developing ideas first... :)

**Comment by ViralBShah** [comment]
@cormullion These are nice - but I worry we'll forget and these will get out of date in a few months. Do you think we can add something updated but more generic (not specific to JuliaCon 2023 or upcoming JuliaCon Eindhoven) so that we are not required to update in a few months?

**Comment by cormullion** [comment]
Thanks! I updated the channel.

As ever, let me know if you want anything...
