### ISSUE TITLE
JuliaCon 2024: Logo Design for 2024 in Eindhoven

### ISSUE THREAD

**Issue by cityjumper** [cormullion/graphics#19]
The Eindhoven logo is:  (with Vibes)
![](https://logos-download.com/wp-content/uploads/2021/01/Eindhoven_Logo.png)

There is a Julia Package that creates the Vibes with Julia Colors.

**Comment by cormullion** [comment]
Thanks! I think I've contributed to that package.

**Comment by DragonflyStats** [comment]
Can we merge this with issue #18

**Comment by cormullion** [comment]
Not sure how to merge, so closing as duplicate...
