### ISSUE TITLE
JuliaCon 2024: LinkedIn Page Event

### ISSUE THREAD

**Issue by cityjumper** [cormullion/graphics#20]
Can we have an updated version for the JuliaCon 2024 LinkedIn page (currently it says 2023 and MIT)

**Comment by cormullion** [comment]
Yes, I'm going to work on it this weekend...

**Comment by DragonflyStats** [comment]
Can we merge this with issue #18

**Comment by cormullion** [comment]
Not sure how to merge, so closing as duplicate...
