### ISSUE TITLE
JuliaCon Requests

### ISSUE THREAD

**Issue by rayegun** [cormullion/graphics#29]
Hi Cormullion :)

Could I get a few requests put together?

- [ ] The JuliaCon 2024 final t-shirt design (I remember some discussion about this but can't recall the outcome). It will need space for ~5-10 logos
- [ ] A horizontal banner (for the registration desk etc)
- [ ] A vertical banner with room for text in the middle (like this floor number or the talks / rooms for that day etc)
- [x] A poster and square template for speakers to advertise themselves (room for a face pic / package pic, and a title and abstract). This is the only really urgent one.

Finally, if you've got any creative designs not on this repo you want me to add to our stickers / storefront let me know raye@julialang.org :)

Hope to see you in Eindhoven!

**Comment by cormullion** [comment]
Hi Raye. Happy to help if I can!

Yes, I opened an issue about the t-shirt with logos idea [here](https://github.com/JuliaCon/www.juliacon.org/issues/506), after I read about it first.  I think I was concerned about the size and colors - but 10 white logos might fit on at a reasonable size I suppose. 

After meeting Kevin last year I made a Mondrian/Dutch-y design with Julia/Eindhoven 'vibes' to make a bright colorful theme - 

<img width="533" alt="Screenshot 2024-04-20 at 10 41 33" src="https://github.com/cormullion/graphics/assets/52289/bfd9dd69-b305-409c-bff5-39cdfb1d914d">

I could continue using it if you like. Or something else if you'd prefer.

**Comment by rayegun** [comment]
I like this logo a lot. @ranjanan agreed? The most pressing of the items would be the poster and square (1:1) templates for speakers to advertise themselves on. Probably something like room for a headshot / picture from their talk and an abstract. 

Could we get one or several of those as soon as you can @cormullion? 

I'll probably put in t-shirt orders around June 5, so we have a bit of time there :).

**Comment by ranjanan** [comment]
This is awesome! Thanks @cormullion. Let's use this for speakers to advertise themselves on.

**Comment by cormullion** [comment]
Could probably squeeze another photo in. But not a lot of room for sponsor logos:

![dagger](https://github.com/cormullion/graphics/assets/52289/d3517860-4ed4-4cb2-b9fa-9560aced3c93)

**Comment by rayegun** [comment]
These look fantastic. Could we get each one blank? And maybe one with 1 photos and 1 with 0 photos for those that don't want them?

**Comment by cormullion** [comment]
Sue, no problem - probably Saturday, am away till then.

**Comment by cormullion** [comment]
`...juliacon2024/2024-templates-1920x1920/*.png`

**Comment by rayegun** [comment]
Thanks a bunch! Alright next order of business is the t-shirt. We definitely want the Mondrian-esque logo (or another design of course that you think might be better on a t-shirt) as the main element of the t-shirt back. I think the logos can be a fair bit smaller than that (but I'm not 100% sure there).

Also, you wouldn't happen to have the YouTube thumbnail backgrounds for the past years available would you? I can't seem to find them all on this repo :). I need to edit some old thumbnails.

**Comment by cormullion** [comment]
>thumbnail backgrounds 

They're all over the place, naming-wise, so I gathered them together here: `backgrounds-2020-2023/2021`.

**Comment by cormullion** [comment]
As for the shirt...

I redrew the logos in SVG (down to and including Supporting Partners, replacing dark text with white, and keeping the colours. (Betterhand Financial have a newer logo I found.)
 
![t-shirt-design-2](https://github.com/cormullion/graphics/assets/52289/be99ff86-61bd-4b95-b9ca-3ee9e15a6ae7)

Does it - will it - work? I don't know. On my high-res screen it looks OK, but what's the resolution of a t-shirt?  And the graphics are getting quite low on the back too.

**Comment by rayegun** [comment]
@cormullion we aren't likely to do too many logos if *any* right now. We removed it from our sponsorship perks, but we may add it back for very high sponsorships (gold+)

Do you think this design would look good?
1. Put the JuliaCon Eindhoven 2024 logos you currently have on the back centered in the front
2. Enlarge the Mondrian design
3. Leave room for maybe 4 logos

**Comment by rayegun** [comment]
Is it weird to have a centered large object on the front @ranjanan @vchuravy? The JuliaCon logo + Eindhoven 2024 beneath it. As opposed to the previous year with just JuliaCon on the left pec.

**Comment by cormullion** [comment]
> centered large object

There’s a slight push back against that - https://geekfeminism.fandom.com/wiki/T-shirts

**Comment by cormullion** [comment]
@rayegun Still on track? 🤔

(Don’t use any of [these designs](https://cormullion.github.io/pages/2024-06-03-rejects/) ) !  😀

**Comment by rayegun** [comment]
> There’s a slight push back against that - https://geekfeminism.fandom.com/wiki/T-shirts

Oh good to know! Let's move forward with the traditional front, and just the conference logo on the back. Currently no sponsors require being on the t-shirt. 

Could we get a final t-shirt as well as a last ditch advertising poster? Suitable to print (letter paper size). Maybe one with room for text that I can add based on the recipient.

Finally I'd like to get to work on the horizontal and vertical banners here soon, if you have a chance. 

I appreciate it as always :)

**Comment by cormullion** [comment]
Hi! 

For a shirt, I was thinking something like this:

![l2](https://github.com/cormullion/graphics/assets/52289/5a7a8d0a-d71a-4aba-abbc-2503b2900f50
)

Or something a bit more off-beat:

![l4](https://github.com/cormullion/graphics/assets/52289/c7a97f14-1821-4de8-9a9b-b388c0bc1001)

For a poster, perhaps something like this:

![flyer-landscape](https://github.com/cormullion/graphics/assets/52289/08e1edfa-8570-48a7-a1f7-54900dfd390b)

Here's a letter-format flier with some space:

![flyer-portrait](https://github.com/cormullion/graphics/assets/52289/ba14ec86-f268-4a76-a7b5-8108fd25b72f)

A horizontal banner:

![banner](https://github.com/cormullion/graphics/assets/52289/fa359f1e-6bd4-4c27-9445-fbe15f09614c)

You'll have to tell me more about a vertical banner (because you did them last time... ;) 

Tell me about which logos you'd like to promote...

Cheers!

**Comment by rayegun** [comment]
Let's go with the first design (the Mondrian version) for the t-shirt. Can I get the transparency version ASAP?

**Comment by cormullion** [comment]
@rayegun Sure:

juliacon2024/shirt-art.png (https://github.com/cormullion/graphics/blob/master/juliacon2024/shirt-art.png)

juliacon2024/shirt-art.svg (https://github.com/cormullion/graphics/blob/master/juliacon2024/shirt-art.svg)

**Comment by rayegun** [comment]
Hey @cormullion could I get a very high resolution of the horizontal banner you just sent? 

Could I also get a version that is agnostic to the year of the conference? So just a JuliaCon horizontal banner, rather than a Juliacon 2024 banner.

I'll send a picture of what I did for vertical banners last year shortly. But in essence just the usual stuff with room for all of the sponsor logos listed on the website! Thanks a bunch for helping out the Julia Gender Inclusive folks!!

**Comment by rayegun** [comment]
Ah well we'll miss having you!

I think the last request I have is for the YouTube thumbnails and stream backgrounds! Similar to last year

**Comment by cormullion** [comment]
How many sponsor logos do you want to display?

**Comment by rayegun** [comment]
I ended up doing the background using last year's background real quick.

The only thing I have remaining is maybe one or two 16:9 templates I can add text and sponsors to. Mostly for opening and closing statement slides. If you have time today to get on this it would be great, but if not don't worry about it :).

And then if you'd like to make a new batch of thumbnail / title images for YouTube of course that would be great, but I have the batches from previous years that are already beautiful and I've edited them with this year's logo.

Thanks for all your help! I'll probably ping you in the next few days about starting to design some new merch for our online store if you're up for that :). The goal is to have a good stable of products we can rotate in and out to provide some extra income for JuliaCon throughout the year. We can also talk about commission and such if you'd like.

**Comment by rayegun** [comment]
Specifically with the 16:9 templates, high definition and plenty of room for text etc. Probably just one of your nice backgrounds or a new one **_without_** any of the overlays or bars on the bottom or side.

**Comment by cormullion** [comment]
This kind of thing: (1920 x 1080)?

<img width="959" alt="Screenshot 2024-07-08 at 11 06 00" src="https://github.com/cormullion/graphics/assets/52289/c19883f0-1a49-4685-bc91-119f4600de82">

**Comment by rayegun** [comment]
Perfect!! Thank you!!

**Comment by rayegun** [comment]
Can you upload that to the repo? For some reason I can't download that image.

**Comment by cormullion** [comment]
Committed: 

juliacon2024/backgrounds-1920-1080/...
