### ISSUE TITLE
Julia Language Indent for PyData NYC

### ISSUE THREAD

**Issue by DragonflyStats** [cormullion/graphics#34]
Hi Cormullion
Would you be able to make an ident for Julia for the PyData NYC CFP 
The idea is to bring in more Julia (and R) talks into that conference.
It will be like the one we posted previously on mastodon
Regards
Kevin

**Comment by DragonflyStats** [comment]
Sorry - got the posts mixed up
I was referring to this one
![Uploading 15b34aaeeeac4efc.png…]()

**Comment by DragonflyStats** [comment]
Whoops - I got one toot mixed up with another one
This is what I meant
https://fosstodon.org/@kobriendublin/112937561363647161

**Comment by cormullion** [comment]
That’s AI though 😀You do the AI ones 🤔

**Comment by DragonflyStats** [comment]
That one is - and I will probably do a few more besides for R. It is fairly straightforward in terms of prompts
There are some good R artists - but conference promotion is a very specific brief. 

But I reckon to check with you first before trying out Julia ones.

**Comment by cormullion** [comment]
No worries! I’m very happy with you being the go-to person for Julia AI-art!

(I’m always here if your prompts fail to deliver what you want 😱😂)

**Comment by DragonflyStats** [comment]
I think we will close this one for now. It was a long shot for 2024, with not enough lead-out time We might have better luck in 2025.
