### ISSUE TITLE
JuliaCon 2020 png Logo

### ISSUE THREAD

**Issue by logankilpatrick** [cormullion/graphics#4]
![juliacon2020](https://user-images.githubusercontent.com/35577566/86031069-391e6300-b9ea-11ea-9aa1-0c2ec1b44149.png)

Here's a PNG of the JuliaCon 2020 Logo to be added to the JuliaCon folder.

**Comment by cormullion** [comment]
I added 500×500 and a 2000×2000 PNGs of this.
