### ISSUE TITLE
LinkedIn Banner

### ISSUE THREAD

**Issue by logankilpatrick** [cormullion/graphics#6]
Hey @cormullion, is it just me or is the banner image: https://github.com/cormullion/graphics/blob/master/juliacon2021/juliacon-2021-linkedin-banner-light-1128x191.png a little blurry? See it in action here: https://www.linkedin.com/events/6746462348694958080/

**Comment by cormullion** [comment]
Yes, it's not very good, is it, the original image probably has a bit too much detail really. :( The original is "only" 1128 pixels wide, so it's never going to be amazing. But they've also resized the image to 800x200 and converted it to JPEG, so I'm not too surprised it looks crummy:

<img width="848" alt="Screenshot 2021-01-19 at 09 04 50" src="https://user-images.githubusercontent.com/52289/105011868-65a4d580-5a35-11eb-802a-7af9f52c029f.png">

The image is zoomed in/cropped when you resize the browser window...

I tried putting the text on a white background:

<img width="358" alt="Screenshot 2021-01-19 at 08 50 36" src="https://user-images.githubusercontent.com/52289/105012008-938a1a00-5a35-11eb-918f-e78b5009b238.png">

but I'm not seeing more pixels in these PNGs, and I don't think it's any better, even before it gets the "treatment"..

So I think this banner should be thrown away and replaced with something simpler and less croppable, although to be honest I'm not very good at that... :)
