### ISSUE TITLE
JuliaCon Banner for Facebook

### ISSUE THREAD

**Issue by logankilpatrick** [cormullion/graphics#7]
Hey! Can we get a JuliaCon banner for Facebook? It would need to be: "Displays at 820 pixels wide by 312 pixels tall on your Page on computers and 640 pixels wide by 360 pixels tall on smartphones." per https://www.facebook.com/help/125379114252045

**Comment by cormullion** [comment]
Will do it tomorrow...

**Comment by cormullion** [comment]
My first thought is:

![juliacon-2021-facebook-banner copy](https://user-images.githubusercontent.com/52289/120463153-868e1780-c393-11eb-9bf2-3bd063269ffc.jpg)

which is 851x360, with the graphics inside 820x312 and 640v360. But the file's a bit big at 328KB. And unfortunately it's a JPEG, so won't be very sharp. (Why do they want PNGs? ☹️ )

Here's a PNG without the gradient (246KB):

![juliacon-2021-facebook-banner copy](https://user-images.githubusercontent.com/52289/120463883-3feced00-c394-11eb-927b-0af9ae6495be.png)

Perhaps see if these work? - we can iterate a bit...
